spring:
  application.name: harmonynow_backend
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/shop
    username: admin_jhhan
    password: admin_jhhan

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

  sql:
    init:
      platform: postgres

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

file:
  path: C:/Users/hanju/harmonynow/
