spring:
  application.name: harmonynow_backend

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging.level:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

file:
  source-base-path: ${SOURCE_BASE_PATH}
  target-base-path: ${TARGET_BASE_PATH}

openai:
  url:
    prompt: ${OPENAI_URL}
  secret-key: ${OPENAI_SECRET_KEY}

model-server:
  url: ${MODEL_SERVER_URL}

admin:
  code: ${ADMIN_CODE}